<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7dbdebc3978f3ee85349c10e2d4f966e
{
    public static $prefixLengthsPsr4 = array (
        'Y' => 
        array (
            'YaelPortfolio\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'YaelPortfolio\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7dbdebc3978f3ee85349c10e2d4f966e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7dbdebc3978f3ee85349c10e2d4f966e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7dbdebc3978f3ee85349c10e2d4f966e::$classMap;

        }, null, ClassLoader::class);
    }
}
